// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAAS_Projectplanningtool.Data;

#nullable disable

namespace SAAS_Projectplanningtool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925072422_ProjectTaskCalculation")]
    partial class ProjectTaskCalculation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultWorkDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWorkingHoursJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsiblePersonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectBudgetId");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("StateId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("InitialBudget")
                        .HasColumnType("real");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("UsedBudget")
                        .HasColumnType("real");

                    b.HasKey("ProjectBudgetId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("ProjectBudget");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectSectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectSectionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StateId");

                    b.HasIndex("SubSectionId");

                    b.ToTable("ProjectSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.Property<string>("ProjectTaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsScheduleEntry")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaskCatalogEntry")
                        .HasColumnType("bit");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectTaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectTaskId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectSectionId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskHourlyRateGroup", b =>
                {
                    b.Property<string>("ProjectTaskHourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("HourlyRateGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectTaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectTaskHourlyRateGroupId");

                    b.HasIndex("HourlyRateGroupId");

                    b.HasIndex("ProjectTaskId");

                    b.ToTable("ProjectTaskHourlyRateGroup");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultWorkDaysJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWorkingHoursJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CompanyId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("SectorId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityRoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HourlyRateGroupId");

                    b.HasIndex("IdentityRoleId");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<float>("HourlyRate")
                        .HasColumnType("real");

                    b.Property<string>("HourlyRateGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HourlyRateGroupId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("HourlyRateGroup");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", b =>
                {
                    b.Property<string>("SectorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorId");

                    b.ToTable("IndustrySector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.LicenseModel", b =>
                {
                    b.Property<string>("LicenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseId");

                    b.ToTable("LicenseModel");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.State", b =>
                {
                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Logfile", b =>
                {
                    b.Property<string>("LogfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcecutingEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedObject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeOfException")
                        .HasColumnType("datetime2");

                    b.HasKey("LogfileId");

                    b.HasIndex("ExcecutingEmployeeId");

                    b.ToTable("Logfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", "ProjectBudget")
                        .WithMany()
                        .HasForeignKey("ProjectBudgetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Customer");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectBudget");

                    b.Navigation("ResponsiblePerson");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ParentSection")
                        .WithMany("SubSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany("ProjectSections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "SubSection")
                        .WithMany()
                        .HasForeignKey("SubSectionId");

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ParentSection");

                    b.Navigation("Project");

                    b.Navigation("State");

                    b.Navigation("SubSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ProjectSection")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectSection");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskHourlyRateGroup", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.HourlyRateGroup", "HourlyRateGroup")
                        .WithMany()
                        .HasForeignKey("HourlyRateGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", "ProjectTask")
                        .WithMany("ProjectTaskHourlyRateGroups")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HourlyRateGroup");

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.LicenseModel", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("License");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Customer", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.HourlyRateGroup", "HourlyRateGroup")
                        .WithMany()
                        .HasForeignKey("HourlyRateGroupId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "IdentityRole")
                        .WithMany()
                        .HasForeignKey("IdentityRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("HourlyRateGroup");

                    b.Navigation("IdentityRole");

                    b.Navigation("IdentityUser");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Logfile", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "ExcecutingEmployee")
                        .WithMany()
                        .HasForeignKey("ExcecutingEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExcecutingEmployee");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.Navigation("ProjectSections");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Navigation("ProjectTasks");

                    b.Navigation("SubSections");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.Navigation("ProjectTaskHourlyRateGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
