// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAAS_Projectplanningtool.Data;

#nullable disable

namespace SAAS_Projectplanningtool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316154451_InitialCreate12")]
    partial class InitialCreate12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ProjectId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectBudgetId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("InitialBudget")
                        .HasColumnType("real");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("UsedBudget")
                        .HasColumnType("real");

                    b.HasKey("ProjectBudgetId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("ProjectBudget");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectSectionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubSectionId");

                    b.ToTable("ProjectSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.Property<string>("ProjectTaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectSectionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectTaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectTaskId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectSectionID");

                    b.ToTable("ProjectTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWorkDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CompanyId");

                    b.HasIndex("AddressId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("SectorId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourlyRateGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityRoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HourlyRateGroupId");

                    b.HasIndex("IdentityRoleId");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("HourlyRate")
                        .HasColumnType("real");

                    b.Property<string>("HourlyRateGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HourlyRateGroupId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId")
                        .IsUnique()
                        .HasFilter("[LatestModifierId] IS NOT NULL");

                    b.ToTable("HourlyRateGroup");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", b =>
                {
                    b.Property<string>("SectorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorId");

                    b.ToTable("IndustrySector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.License", b =>
                {
                    b.Property<string>("LicenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.State", b =>
                {
                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.ProjectTaskRessource", b =>
                {
                    b.Property<string>("ProjectTaskRessourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("AmountPerUnit")
                        .HasColumnType("real");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectTaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RessourceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectTaskRessourceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectTaskId");

                    b.HasIndex("RessourceId");

                    b.ToTable("ProjectTaskRessource");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.Ressource", b =>
                {
                    b.Property<string>("RessourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("CostsPerUnit")
                        .HasColumnType("real");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RessourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RessourceTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnitId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RessourceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("RessourceTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("Ressource");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.RessourceType", b =>
                {
                    b.Property<string>("RessourceTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsEmployeeRessourceType")
                        .HasColumnType("bit");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RessourceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RessourceTypeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("RessourceType");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.Unit", b =>
                {
                    b.Property<string>("UnitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", "ProjectBudget")
                        .WithMany()
                        .HasForeignKey("ProjectBudgetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("LatestModidier");

                    b.Navigation("ProjectBudget");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ParentSection")
                        .WithMany("SubSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "SubSection")
                        .WithMany()
                        .HasForeignKey("SubSectionId");

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");

                    b.Navigation("ParentSection");

                    b.Navigation("Project");

                    b.Navigation("SubSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ProjectSection")
                        .WithMany()
                        .HasForeignKey("ProjectSectionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");

                    b.Navigation("ProjectSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("License");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Customer", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.HourlyRateGroup", "HourlyRateGroup")
                        .WithMany()
                        .HasForeignKey("HourlyRateGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "IdentityRole")
                        .WithMany()
                        .HasForeignKey("IdentityRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("HourlyRateGroup");

                    b.Navigation("IdentityRole");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithOne()
                        .HasForeignKey("SAAS_Projectplanningtool.Models.HourlyRateGroup", "LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.ProjectTaskRessource", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", "ProjectTask")
                        .WithMany()
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Ressourceplanning.Ressource", "Ressource")
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");

                    b.Navigation("ProjectTask");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.Ressource", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Ressourceplanning.RessourceType", "RessourceType")
                        .WithMany()
                        .HasForeignKey("RessourceTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Ressourceplanning.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");

                    b.Navigation("RessourceType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.RessourceType", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Ressourceplanning.Unit", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModidier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("LatestModidier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Navigation("SubSections");
                });
#pragma warning restore 612, 618
        }
    }
}
