// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAAS_Projectplanningtool.Data;

#nullable disable

namespace SAAS_Projectplanningtool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401210204_HRGDecimal")]
    partial class HRGDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.ArticleManagement.Article", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleCategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.ArticleManagement.ArticleCategory", b =>
                {
                    b.Property<string>("ArticleCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ArticleCategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("ArticleCategory");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.BudgetRecalculation", b =>
                {
                    b.Property<string>("RecalculationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("NewBudget")
                        .HasColumnType("float");

                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecalculatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RecalculationDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RecalculationId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProjectBudgetId");

                    b.HasIndex("RecalculatedById");

                    b.ToTable("BudgetRecalculation");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultWorkDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWorkingHoursJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLeadId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectBudgetId");

                    b.HasIndex("ProjectLeadId");

                    b.HasIndex("StateId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectAdditionalCosts", b =>
                {
                    b.Property<string>("ProjectAdditionalCostsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("AdditionalCostAmount")
                        .HasColumnType("float");

                    b.Property<string>("AdditionalCostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectAdditionalCostsId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectAdditionalCosts");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("InitialBudget")
                        .HasColumnType("float");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectBudgetId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("ProjectBudget");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectHourlyRateGroup", b =>
                {
                    b.Property<string>("ProjectHourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("ProjectHourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectHourlyRateGroupId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HourlyRateGroupId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectHourlyRateGroup");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectSectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectSectionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSectionMilestone", b =>
                {
                    b.Property<string>("ProjectSectionMilestoneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MilestoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectSectionMilestoneId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectSectionId");

                    b.ToTable("ProjectSectionMilestone");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.Property<string>("ProjectTaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectTaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectTaskId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectSectionId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskCatalogTask", b =>
                {
                    b.Property<string>("ProjectTaskCatalogTaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectTaskCatalogTaskId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectTaskCatalogTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.ContactHistoryEntry", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ContactDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.ToTable("ContactHistoryEntry");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.CustomerContactPerson", b =>
                {
                    b.Property<string>("ContactPersonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactPersonId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerContactPerson");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.CustomerMaterialSurcharge", b =>
                {
                    b.Property<string>("SurchargeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SurchargePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SurchargeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerMaterialSurcharge");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.CustomerMessage", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ClosedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.HasIndex("ClosedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerMessage");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultWorkDaysJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWorkingHoursJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CompanyId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("SectorId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HourlyRateGroupId");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HolidayCalendarEntry", b =>
                {
                    b.Property<string>("HolidayCalendarEntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HolidayType")
                        .HasColumnType("int");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HolidayCalendarEntryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("CompanyId", "HolidayDate");

                    b.ToTable("HolidayCalendarEntry");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HourlyRateGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HourlyRateGroupId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("HourlyRateGroup");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", b =>
                {
                    b.Property<string>("SectorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorId");

                    b.ToTable("IndustrySector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.LicenseModel", b =>
                {
                    b.Property<string>("LicenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseId");

                    b.ToTable("LicenseModel");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.State", b =>
                {
                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Logfile", b =>
                {
                    b.Property<string>("LogfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcecutingEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedObject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeOfException")
                        .HasColumnType("datetime2");

                    b.HasKey("LogfileId");

                    b.HasIndex("ExcecutingEmployeeId");

                    b.ToTable("Logfile");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.ProjectEmployeeViewerShare", b =>
                {
                    b.Property<string>("ProjectEmployeeShareId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectEmployeeShareId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectEmployeeViewerShare");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.TimeTracking.TimeEntry", b =>
                {
                    b.Property<string>("TimeEntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TimeEntry");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.ArticleManagement.Article", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.ArticleManagement.ArticleCategory", "ArticleCategory")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ArticleCategory");

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.ArticleManagement.ArticleCategory", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.BudgetRecalculation", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", null)
                        .WithMany("BudgetRecalculations")
                        .HasForeignKey("ProjectBudgetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "RecalculatedBy")
                        .WithMany()
                        .HasForeignKey("RecalculatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("RecalculatedBy");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.CRM.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", "ProjectBudget")
                        .WithMany()
                        .HasForeignKey("ProjectBudgetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "ProjectLead")
                        .WithMany()
                        .HasForeignKey("ProjectLeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Customer");

                    b.Navigation("Instructor");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectBudget");

                    b.Navigation("ProjectLead");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectAdditionalCosts", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany("ProjectAdditionalCosts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget+InitialAdditionalCost", "InitialAdditionalCosts", b1 =>
                        {
                            b1.Property<string>("ProjectBudgetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<double>("AdditionalCostAmount")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalCostName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectBudgetId", "Id");

                            b1.ToTable("ProjectBudget");

                            b1.ToJson("InitialAdditionalCosts");

                            b1.WithOwner()
                                .HasForeignKey("ProjectBudgetId");
                        });

                    b.OwnsMany("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget+InitialHRGPlanning", "InitialHRGPlannings", b1 =>
                        {
                            b1.Property<string>("ProjectBudgetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("Amount")
                                .HasColumnType("int");

                            b1.Property<double>("EstimatedHours")
                                .HasColumnType("float");

                            b1.Property<decimal>("HourlyRate")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("HourlyRateGroupId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HourlyRateGroupName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectBudgetId", "Id");

                            b1.ToTable("ProjectBudget");

                            b1.ToJson("InitialHRGPlannings");

                            b1.WithOwner()
                                .HasForeignKey("ProjectBudgetId");
                        });

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("InitialAdditionalCosts");

                    b.Navigation("InitialHRGPlannings");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectHourlyRateGroup", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.HourlyRateGroup", "HourlyRateGroup")
                        .WithMany()
                        .HasForeignKey("HourlyRateGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("HourlyRateGroup");

                    b.Navigation("LatestModifier");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ParentSection")
                        .WithMany("SubSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany("ProjectSections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ParentSection");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSectionMilestone", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ProjectSection")
                        .WithMany("ProjectSectionMilestones")
                        .HasForeignKey("ProjectSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ProjectSection")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectSection");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskCatalogTask", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany("ProjectTaskCatalogTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.ContactHistoryEntry", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.CRM.Customer", "Customer")
                        .WithMany("ContactHistoryEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.Customer", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.CustomerContactPerson", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.CRM.Customer", "Customer")
                        .WithMany("ContactPersons")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.CustomerMaterialSurcharge", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.CRM.Customer", "Customer")
                        .WithMany("MaterialSurcharges")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.CustomerMessage", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "ClosedByEmployee")
                        .WithMany()
                        .HasForeignKey("ClosedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.CRM.Customer", "Customer")
                        .WithMany("CustomerMessages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClosedByEmployee");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.LicenseModel", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("License");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.HourlyRateGroup", "HourlyRateGroup")
                        .WithMany()
                        .HasForeignKey("HourlyRateGroupId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("HourlyRateGroup");

                    b.Navigation("IdentityUser");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HolidayCalendarEntry", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Logfile", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "ExcecutingEmployee")
                        .WithMany()
                        .HasForeignKey("ExcecutingEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExcecutingEmployee");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.ProjectEmployeeViewerShare", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LatestModifier");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.TimeTracking.TimeEntry", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LatestModifier");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.ArticleManagement.ArticleCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.Navigation("ProjectAdditionalCosts");

                    b.Navigation("ProjectSections");

                    b.Navigation("ProjectTaskCatalogTasks");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.Navigation("BudgetRecalculations");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Navigation("ProjectSectionMilestones");

                    b.Navigation("ProjectTasks");

                    b.Navigation("SubSections");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.CRM.Customer", b =>
                {
                    b.Navigation("ContactHistoryEntries");

                    b.Navigation("ContactPersons");

                    b.Navigation("CustomerMessages");

                    b.Navigation("MaterialSurcharges");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
