// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAAS_Projectplanningtool.Data;

#nullable disable

namespace SAAS_Projectplanningtool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207131939_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.HasKey("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.BudgetRecalculation", b =>
                {
                    b.Property<string>("RecalculationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<double>("NewBudget")
                        .HasColumnType("REAL");

                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecalculatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecalculationDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("RecalculationId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProjectBudgetId");

                    b.HasIndex("RecalculatedById");

                    b.ToTable("BudgetRecalculation");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWorkDays")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWorkingHoursJson")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsiblePersonId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectBudgetId");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("StateId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectAdditionalCosts", b =>
                {
                    b.Property<string>("ProjectAdditionalCostsId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdditionalCostAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("AdditionalCostName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectAdditionalCostsId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectAdditionalCosts");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.Property<string>("ProjectBudgetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("InitialBudget")
                        .HasColumnType("REAL");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectBudgetId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("ProjectBudget");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectSectionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectSectionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSectionMilestone", b =>
                {
                    b.Property<string>("ProjectSectionMilestoneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MilestoneName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectSectionMilestoneId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectSectionId");

                    b.ToTable("ProjectSectionMilestone");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.Property<string>("ProjectTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectTaskName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectTaskId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectSectionId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskCatalogTask", b =>
                {
                    b.Property<string>("ProjectTaskCatalogTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectTaskFixCostsId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectTaskCatalogTaskId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectTaskFixCostsId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectTaskCatalogTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskFixCosts", b =>
                {
                    b.Property<string>("ProjectTaskFixCostsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectTaskFixCostsId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("ProjectTaskFixCosts");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskHourlyRateGroup", b =>
                {
                    b.Property<string>("ProjectTaskHourlyRateGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HourlyRateGroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectTaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectTaskHourlyRateGroupId");

                    b.HasIndex("HourlyRateGroupId");

                    b.HasIndex("ProjectTaskId");

                    b.ToTable("ProjectTaskHourlyRateGroup");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWorkDaysJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWorkingHoursJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectorId")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("SectorId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityRoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HourlyRateGroupId");

                    b.HasIndex("IdentityRoleId");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.Property<string>("HourlyRateGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("INTEGER");

                    b.Property<float>("HourlyRate")
                        .HasColumnType("REAL");

                    b.Property<string>("HourlyRateGroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModificationText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestModifierId")
                        .HasColumnType("TEXT");

                    b.HasKey("HourlyRateGroupId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LatestModifierId");

                    b.ToTable("HourlyRateGroup");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", b =>
                {
                    b.Property<string>("SectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SectorId");

                    b.ToTable("IndustrySector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.LicenseModel", b =>
                {
                    b.Property<string>("LicenseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("LicenseId");

                    b.ToTable("LicenseModel");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.IndependentTables.State", b =>
                {
                    b.Property<string>("StateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Logfile", b =>
                {
                    b.Property<string>("LogfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcecutingEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedObject")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOfException")
                        .HasColumnType("TEXT");

                    b.HasKey("LogfileId");

                    b.HasIndex("ExcecutingEmployeeId");

                    b.ToTable("Logfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Address", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.BudgetRecalculation", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", null)
                        .WithMany("BudgetRecalculations")
                        .HasForeignKey("ProjectBudgetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "RecalculatedBy")
                        .WithMany()
                        .HasForeignKey("RecalculatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("RecalculatedBy");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", "ProjectBudget")
                        .WithMany()
                        .HasForeignKey("ProjectBudgetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Customer");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectBudget");

                    b.Navigation("ResponsiblePerson");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectAdditionalCosts", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany("ProjectAdditionalCosts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget+InitialAdditionalCost", "InitialAdditionalCosts", b1 =>
                        {
                            b1.Property<string>("ProjectBudgetId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<double>("AdditionalCostAmount")
                                .HasColumnType("REAL");

                            b1.Property<string>("AdditionalCostName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectBudgetId", "Id");

                            b1.ToTable("ProjectBudget");

                            b1.ToJson("InitialAdditionalCosts");

                            b1.WithOwner()
                                .HasForeignKey("ProjectBudgetId");
                        });

                    b.OwnsMany("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget+InitialHRGPlanning", "InitialHRGPlannings", b1 =>
                        {
                            b1.Property<string>("ProjectBudgetId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Amount")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("EstimatedHours")
                                .HasColumnType("REAL");

                            b1.Property<decimal>("HourlyRate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("HourlyRateGroupId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("HourlyRateGroupName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectBudgetId", "Id");

                            b1.ToTable("ProjectBudget");

                            b1.ToJson("InitialHRGPlannings");

                            b1.WithOwner()
                                .HasForeignKey("ProjectBudgetId");
                        });

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("InitialAdditionalCosts");

                    b.Navigation("InitialHRGPlannings");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ParentSection")
                        .WithMany("SubSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany("ProjectSections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ParentSection");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSectionMilestone", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ProjectSection")
                        .WithMany("ProjectSectionMilestones")
                        .HasForeignKey("ProjectSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectSection");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", "ProjectSection")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("ProjectSection");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskCatalogTask", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.Project", "Project")
                        .WithMany("ProjectTaskCatalogTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskFixCosts", "ProjectTaskFixCosts")
                        .WithMany()
                        .HasForeignKey("ProjectTaskFixCostsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("Project");

                    b.Navigation("ProjectTaskFixCosts");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskFixCosts", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskCatalogTask", "ProjectTaskCatalogTask")
                        .WithOne()
                        .HasForeignKey("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskFixCosts", "TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskFixCosts+FixCost", "FixCosts", b1 =>
                        {
                            b1.Property<string>("ProjectTaskFixCostsId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<double?>("Cost")
                                .HasColumnType("REAL");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectTaskFixCostsId", "Id");

                            b1.ToTable("ProjectTaskFixCosts");

                            b1.ToJson("FixCosts");

                            b1.WithOwner()
                                .HasForeignKey("ProjectTaskFixCostsId");
                        });

                    b.Navigation("FixCosts");

                    b.Navigation("ProjectTaskCatalogTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTaskHourlyRateGroup", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.HourlyRateGroup", "HourlyRateGroup")
                        .WithMany()
                        .HasForeignKey("HourlyRateGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", "ProjectTask")
                        .WithMany("ProjectTaskHourlyRateGroups")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HourlyRateGroup");

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Company", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.LicenseModel", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.IndependentTables.IndustrySector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");

                    b.Navigation("License");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Customer", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Employee", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.HourlyRateGroup", "HourlyRateGroup")
                        .WithMany()
                        .HasForeignKey("HourlyRateGroupId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "IdentityRole")
                        .WithMany()
                        .HasForeignKey("IdentityRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("HourlyRateGroup");

                    b.Navigation("IdentityRole");

                    b.Navigation("IdentityUser");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.HourlyRateGroup", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "LatestModifier")
                        .WithMany()
                        .HasForeignKey("LatestModifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LatestModifier");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Logfile", b =>
                {
                    b.HasOne("SAAS_Projectplanningtool.Models.Employee", "ExcecutingEmployee")
                        .WithMany()
                        .HasForeignKey("ExcecutingEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExcecutingEmployee");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.Project", b =>
                {
                    b.Navigation("ProjectAdditionalCosts");

                    b.Navigation("ProjectSections");

                    b.Navigation("ProjectTaskCatalogTasks");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectBudget", b =>
                {
                    b.Navigation("BudgetRecalculations");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectSection", b =>
                {
                    b.Navigation("ProjectSectionMilestones");

                    b.Navigation("ProjectTasks");

                    b.Navigation("SubSections");
                });

            modelBuilder.Entity("SAAS_Projectplanningtool.Models.Budgetplanning.ProjectTask", b =>
                {
                    b.Navigation("ProjectTaskHourlyRateGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
